### ISSUE TITLE
Inconsistent use of Copyright statements

### ISSUE THREAD

**Issue by cloudpay-simon** [cmoine/generic-enums#4]
Hi Christophe,

While working on another PR I've noticed that some files include "Copyright Google LLC". I suspect this is a copy'n'paste error as they are all pom.xml files. They also mention the Apache license.

I'd just like to clarify that this project falls under the MIT license.

You can see the affected files here: https://github.com/cmoine/generic-enums/search?q=copyright

Cheers,
Simon

**Comment by cmoine** [comment]
I will fix this, thx you very much!

**Comment by cmoine** [comment]
https://github.com/cmoine/generic-enums/pull/7
